name: voltis_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/core/Images/reply-arrow-icon.png
    - lib/core/Images/profile.png
    - lib/core/Images/demo.png
    - lib/core/Images/avatar.png
    - lib/core/helpers/fonts/Avenir.otf
  fonts:
    - family: Avenir
      fonts:
        - asset: lib/core/helpers/fonts/Avenir.otf

